
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include_dir_merge_named themes

python_script:

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload
    
discovery:

apple_tv:

camera:
  # Alert images from Blue Iris
  - platform: mqtt
    name: Camera1 Alert
    unique_id: camera.camera1_alert
    topic: BI/camera1/alert-image
    
influxdb:
  host: !secret influxdb_server
  port: !secret influxdb_port
  database: !secret influxdb_db
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  
recorder:
  db_url: !secret recorder_db_url
  
sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_free
      - type: memory_use_percent
      - type: disk_use_percent
        arg: /
      - type: disk_use
      - type: disk_free