frontend:
  themes: !include_dir_merge_named ../../hki-base/themes/advanced/
input_text:
  opacity_on:
  opacity_off:
  opacity_unavailable:
  card_box_shadow_light_color:

  # HKI Advanced Theming (Light)
  color_unavailable:
  header_badge_icon_color:
  header_badge_background:
  header_badge_color:
  header_badge_text_color:
  header_border_radius:
  header_box_shadow:
  footer_box_shadow:
  nav_bar_color:
  nav_bar_text_color:
  card_color:
  card_border_style:
  card_border_width:
  card_border_color:
  card_border_radius:
  card_box_shadow:
  header_color:
  header_text_color:
  text_color:
  secondary_text_color:
  background_image:
  icon_color_default:
  icon_color_active:
  font_family:
  header_font_size:
  header_font_weight:
  subtitle_font_size:
  subtitle_font_weight:
  subtitle_text_color:
  title_text_color:
  title_text_font_size:
  title_text_font_weight:
  title_text_background_color:
  title_text_justify_self:
  title_text_border_radius:
  title_text_box_shadow:
  title_text_padding:
  title_text_border_style:
  title_text_border_width:
  title_text_border_color:
  button_color_active:
  button_name_font_size:
  button_name_font_weight:
  button_label_font_size:
  button_label_font_weight:
  button_state_font_size:
  button_state_font_weight:
  button_name_color:
  button_name_color_active:
  button_label_color:
  button_label_color_active:
  button_state_color:
  button_state_color_active:
  badge_background_color:
  badge_text_color:
  badge_font_size:
  badge_font_weight:
  badge_text_transform:
  button_box_shadow_active:
  lock_color_active:
  lock_color_inactive:

  # HKI Advanced Theming (Dark)
  dark_color_unavailable:
  dark_lock_color_active:
  dark_lock_color_inactive:
  dark_header_box_shadow:
  dark_button_box_shadow_active:
  dark_footer_box_shadow:
  dark_header_border_radius:
  dark_header_badge_icon_color:
  dark_header_badge_background:
  dark_header_badge_color:
  dark_header_badge_text_color:
  dark_nav_bar_color:
  dark_nav_bar_text_color:
  dark_card_color:
  dark_card_border_style:
  dark_card_border_width:
  dark_card_border_color:
  dark_card_border_radius:
  dark_card_box_shadow:
  dark_header_color:
  dark_header_text_color:
  dark_text_color:
  dark_secondary_text_color:
  dark_background_image:
  dark_icon_color_default:
  dark_icon_color_active:
  dark_font_family:
  dark_header_font_size:
  dark_header_font_weight:
  dark_subtitle_font_size:
  dark_subtitle_font_weight:
  dark_subtitle_text_color:
  dark_title_text_color:
  dark_title_text_font_size:
  dark_title_text_font_weight:
  dark_title_text_background_color:
  dark_title_text_justify_self:
  dark_title_text_border_radius:
  dark_title_text_box_shadow:
  dark_title_text_padding:
  dark_title_text_border_style:
  dark_title_text_border_width:
  dark_title_text_border_color:
  dark_button_color_active:
  dark_button_name_font_size:
  dark_button_name_font_weight:
  dark_button_label_font_size:
  dark_button_label_font_weight:
  dark_button_state_font_size:
  dark_button_state_font_weight:
  dark_button_name_color:
  dark_button_name_color_active:
  dark_button_label_color:
  dark_button_label_color_active:
  dark_button_state_color:
  dark_button_state_color_active:
  dark_badge_font_size:
  dark_badge_font_weight:
  dark_badge_text_transform:
  dark_badge_background_color:
  dark_badge_text_color: